In [1]:
import yfinance as yf
import pandas as pd
import numpy as npy
import matplotlib.pyplot as plt
import seaborn as sbn

In [2]:
df = yf.download('AAPL', period='5y')

[*********************100%***********************]  1 of 1 completed

In [3]:
df.head()

Price            Close        High         Low        Open     Volume
Ticker            AAPL        AAPL        AAPL        AAPL       AAPL
Date
2021-04-05  122.626045  122.879286  119.869636  120.648835   88651200
2021-04-06  122.927986  123.824060  122.382551  123.210446   80171300
2021-04-07  124.574028  124.593505  121.885798  122.557858   83466700
2021-04-08  126.970070  126.999289  125.177922  125.596732   88844600
2021-04-09  129.541443  129.580396  126.103239  126.424659  106686700

In [4]:
df.info()

<class 'pandas.DataFrame'>
DatetimeIndex: 1256 entries, 2021-04-05 to 2026-04-02
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   (Close, AAPL)   1256 non-null   float64
 1   (High, AAPL)    1256 non-null   float64
 2   (Low, AAPL)     1256 non-null   float64
 3   (Open, AAPL)    1256 non-null   float64
 4   (Volume, AAPL)  1256 non-null   int64
dtypes: float64(4), int64(1)
memory usage: 58.9 KB

In [5]:
df.describe()

Price         Close         High          Low         Open        Volume
Ticker         AAPL         AAPL         AAPL         AAPL          AAPL
count   1256.000000  1256.000000  1256.000000  1256.000000  1.256000e+03
mean     186.108945   187.940180   184.114873   185.932791  6.673499e+07
std       41.699173    42.018310    41.386099    41.726048  2.834047e+07
min      119.780548   121.605016   119.273213   120.161050  1.791060e+07
25%      150.120003   151.859058   148.218018   149.937268  4.691878e+07
50%      175.898384   177.613429   174.386095   175.686676  6.001490e+07
75%      220.658684   222.945456   218.291066   220.165946  7.975090e+07
max      285.922455   288.350192   283.035157   285.932471  3.186799e+08

In [6]:
data_size = len(df)
train_df = df.iloc[:int(data_size * 0.7)]
val_df = df.iloc[int(data_size * 0.7):int(data_size * 0.85)]
test_df = df.iloc[int(data_size * 0.85):]

In [7]:
print(f'Train set shape: {train_df.shape}')
print(f'Val set shape:   {val_df.shape}')
print(f'Test set shape:  {test_df.shape}')
if train_df.shape[0] + val_df.shape[0] + test_df.shape[0] == data_size:
    print('Data split correctly!')
else:
    print('Data was not split correctly!')

Train set shape: (879, 5)
Val set shape:   (188, 5)
Test set shape:  (189, 5)
Data split correctly!

In [11]:
df['SMA10'] = df['Close'].rolling(10).mean()
df['SMA50'] = df['Close'].rolling(50).mean()
df[['Close', 'SMA10', 'SMA50']].head(50)

Price            Close       SMA10      SMA50
Ticker            AAPL
Date
2021-04-05  122.626045         NaN        NaN
2021-04-06  122.927986         NaN        NaN
2021-04-07  124.574028         NaN        NaN
2021-04-08  126.970070         NaN        NaN
2021-04-09  129.541443         NaN        NaN
2021-04-12  127.827171         NaN        NaN
2021-04-13  130.934250         NaN        NaN
2021-04-14  128.596634         NaN        NaN
2021-04-15  131.002426         NaN        NaN
2021-04-16  130.671280  127.567133        NaN
2021-04-19  131.333557  128.437885        NaN
2021-04-20  129.648590  129.109945        NaN
2021-04-21  130.028427  129.655385        NaN
2021-04-22  128.508987  129.809277        NaN
2021-04-23  130.827103  129.937843        NaN
2021-04-26  131.216675  130.276793        NaN
2021-04-27  130.895233  130.272891        NaN
2021-04-28  130.106323  130.423860        NaN
2021-04-29  130.008957  130.324513        NaN
2021-04-30  128.041428  130.061528        NaN
2021-05-03  129.093414  129.837514        NaN
2021-05-04  124.525330  129.325188        NaN
2021-05-05  124.768829  128.799228        NaN
2021-05-06  126.366203  128.584949        NaN
2021-05-07  127.039413  128.206181        NaN
2021-05-10  123.761200  127.460633        NaN
2021-05-11  122.844093  126.655519        NaN
2021-05-12  119.780548  125.622942        NaN
2021-05-13  121.926956  124.814742        NaN
2021-05-14  124.346573  124.445256        NaN
2021-05-17  123.195312  123.855446        NaN
2021-05-18  121.809891  123.583902        NaN
2021-05-19  121.653793  123.272398        NaN
2021-05-20  124.209991  123.056777        NaN
2021-05-21  122.375771  122.590413        NaN
2021-05-24  124.005112  122.614804        NaN
2021-05-25  123.809998  122.711395        NaN
2021-05-26  123.761200  123.109460        NaN
2021-05-27  122.229424  123.139706        NaN
2021-05-28  121.575752  122.862624        NaN
2021-06-01  121.253769  122.668470        NaN
2021-06-02  122.014771  122.688958        NaN
2021-06-03  120.531799  122.576759        NaN
2021-06-04  122.824585  122.438218        NaN
2021-06-07  122.834328  122.484074        NaN
2021-06-08  123.653885  122.448951        NaN
2021-06-09  124.034386  122.471390        NaN
2021-06-10  123.039238  122.399194        NaN
2021-06-11  124.249008  122.601152        NaN
2021-06-14  127.302795  123.173856  125.62208